export const events = [
  {
    // slug: "react-conf-2024",
    image: "/images/event1.png",
    title: "React Conf 2024",
    description:
      "The React Conference brings together the brightest minds in front-end development for a day of learning, networking, and hands-on exploration. From React fundamentals to cutting-edge patterns, performance optimization, and the newest features in the ecosystem, this event is designed to inspire developers of all levels. Hear from top speakers, connect with peers, and walk away with practical skills you can apply immediately to your projects.",
    location: "San Francisco, CA",
    venue: "Convention Center",
    mode: "hybrid",
    audience: "developers,Designers",
    agenda: [
      "Future of React",
      "React Security",
      "React Architecture",
      "React Development",
    ],
    organizer: "React Conf",
    tags: ["react", "javascript", "frontend", "development"],
    date: "March 15, 2024",
    time: "9:00 AM - 6:00 PM",
  },
  {
    // slug: "nextjs-summit",
    image: "/images/event2.png",
    title: "Next.js Summit",
    description:
      "Next.js Summit is a premier event for developers and enthusiasts to explore the latest advancements in Next.js. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "Austin, TX",
    venue: "Convention Center",
    mode: "hybrid",
    audience: "developers,Designers",
    agenda: [
      "Future of Next.js",
      "Next.js Security",
      "Next.js Architecture",
      "Next.js Development",
    ],
    organizer: "Next.js Summit",
    tags: ["nextjs", "javascript", "frontend", "development"],
    date: "April 22, 2024",
    time: "10:00 AM - 5:00 PM",
  },
  {
    //   slug: "javascript-world",
    image: "/images/event3.png",
    title: "JavaScript World Conference",
    description:
      "JavaScript World Conference is a premier event for developers and enthusiasts to explore the latest advancements in JavaScript. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "New York, NY",
    venue: "Convention Center",
    mode: "hybrid",
    audience: "developers,Designers",
    agenda: [
      "Future of JavaScript",
      "JavaScript Security",
      "JavaScript Architecture",
      "JavaScript Development",
    ],
    organizer: "JavaScript World Conference",
    tags: ["javascript", "frontend", "development"],
    date: "May 8, 2024",
    time: "8:30 AM - 7:00 PM",
  },
  {
    slug: "ai-hackathon-2024",
    image: "/images/event4.png",
    title: "AI Innovation Hackathon",
    description:
      "AI Innovation Hackathon is a premier event for developers and enthusiasts to explore the latest advancements in AI. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "Seattle, WA",
    venue: "Convention Center",
    mode: "hybrid",
    audience: "developers,Designers",
    agenda: [
      "Future of AI",
      "AI Security",
      "AI Architecture",
      "AI Development",
    ],
    organizer: "AI Innovation Hackathon",
    tags: ["ai", "hackathon", "development"],
    date: "June 14-16, 2024",
    time: "48 Hours",
  },
  {
    slug: "web3-developer-meetup",
    image: "/images/event5.png",
    title: "Web3 Developer Meetup",
    description:
      "Web3 Developer Meetup is a premier event for developers and enthusiasts to explore the latest advancements in Web3. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "Miami, FL",
    venue: "Convention Center",
    mode: "hybrid",
    audience: "developers,Designers",
    agenda: [
      "Future of Web3",
      "Web3 Security",
      "Web3 Architecture",
      "Web3 Development",
    ],
    organizer: "Web3 Developer Meetup",
    tags: ["web3", "meetup", "development"],
    date: "July 20, 2024",
    time: "6:00 PM - 9:00 PM",
  },
  {
    slug: "fullstack-conference",
    image: "/images/event6.png",
    title: "Full Stack Conference",
    description:
      "Full Stack Conference is a premier event for developers and enthusiasts to explore the latest advancements in Full Stack. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "Denver, CO",
    venue: "Convention Center",
    mode: "hybrid",
    audience: "developers,Designers",
    agenda: [
      "Future of Full Stack",
      "Full Stack Security",
      "Full Stack Architecture",
      "Full Stack Development",
    ],
    organizer: "Full Stack Conference",
    tags: ["fullstack", "conference", "development"],
    date: "August 12, 2024",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "devops-unleashed",
    image: "/images/event1.png",
    title: "DevOps Unleashed",
    description:
      "DevOps Unleashed is a premier event for developers and enthusiasts to explore the latest advancements in DevOps. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "Chicago, IL",
    venue: "Convention Center",
    mode: "hybrid",
    audience: "developers,Designers",
    agenda: [
      "Future of DevOps",
      "DevOps Security",
      "DevOps Architecture",
      "DevOps Development",
    ],
    organizer: "DevOps Unleashed",
    tags: ["devops", "unleashed", "development"],
    date: "September 5, 2024",
    time: "8:00 AM - 5:30 PM",
  },
  {
    slug: "mobile-dev-summit",
    image: "/images/event2.png",
    title: "Mobile Development Summit",
    description:
      "Mobile Development Summit is a premier event for developers and enthusiasts to explore the latest advancements in Mobile Development. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "Los Angeles, CA",
    venue: "Convention Center",
    mode: "hybrid",
    audience: "developers,Designers",
    agenda: [
      "Future of Mobile Development",
      "Mobile Development Security",
      "Mobile Development Architecture",
      "Mobile Development Development",
    ],
    organizer: "Mobile Development Summit",
    tags: ["mobile", "development", "summit"],
    date: "October 18, 2024",
    time: "9:30 AM - 6:00 PM",
  },
  {
    slug: "cybersecurity-conference",
    image: "/images/event3.png",
    title: "Cybersecurity Conference",
    description:
      "Cybersecurity Conference is a premier event for developers and enthusiasts to explore the latest advancements in Cybersecurity. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "Boston, MA",
    venue: "Convention Center",
    mode: "hybrid",
    audience: "developers,Designers",
    agenda: [
      "Future of Cybersecurity",
      "Cybersecurity Security",
      "Cybersecurity Architecture",
      "Cybersecurity Development",
    ],
    organizer: "Cybersecurity Conference",
    tags: ["cybersecurity", "conference", "development"],
    date: "November 2, 2024",
    time: "8:00 AM - 7:00 PM",
  },
  {
    slug: "data-science-hackathon",
    image: "/images/event4.png",
    title: "Data Science Hackathon",
    description:
      "Data Science Hackathon is a premier event for developers and enthusiasts to explore the latest advancements in Data Science. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "San Diego, CA",
    venue: "University Hall",
    mode: "hybrid",
    audience: "developers,Designers",
    agenda: [
      "Future of Data Science",
      "Data Science Security",
      "Data Science Architecture",
      "Data Science Development",
    ],
    organizer: "Data Science Hackathon",
    tags: ["data", "science", "hackathon", "development"],
    date: "December 7-9, 2024",
    time: "72 Hours",
  },
  {
    slug: "cloud-native-meetup",
    image: "/images/event5.png",
    title: "Cloud Native Meetup",
    description:
      "Cloud Native Meetup is a premier event for developers and enthusiasts to explore the latest advancements in Cloud Native. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "Portland, OR",
    venue: "Convention Center",
    mode: "hybrid",
    audience: "devops,developers,Designers",
    agenda: [
      "Future of Cloud Native",
      "Cloud Native Security",
      "Cloud Native Architecture",
      "Cloud Native Development",
    ],
    organizer: "Cloud Native Meetup",
    tags: ["cloud", "native", "meetup", "development"],
    date: "January 15, 2025",
    time: "6:30 PM - 9:00 PM",
  },
  {
    slug: "frontend-masters",
    image: "/images/event6.png",
    title: "Frontend Masters Conference",
    description:
      "Frontend Masters Conference is a premier event for developers and enthusiasts to explore the latest advancements in Frontend Development. This conference features expert speakers, hands-on workshops, and a deep dive into the latest features and best practices. Attendees will gain valuable insights into building server-side rendered applications, server components, and serverless functions, as well as learn how to optimize performance and security. Join us for an engaging experience that will help you stay ahead of the curve in the fast-paced world of web development.",
    location: "Nashville, TN",
    venue: "Anz Stadium",
    mode: "OnSite",
    audience: "UX/UI Designers, developers,Designers",
    agenda: [
      "Future of Frontend Development",
      "Frontend Security",
      "Frontend Architecture",
      "Frontend Development",
    ],
    organizer: "Frontend Masters Conference",
    tags: ["frontend", "UX/UI", "conference", "development"],
    date: "February 28, 2026",
    time: "9:00 AM - 5:00 PM",
  },
];
